- Infra:
    - Homepage:
        href: http://192.168.1.100:3000
        description: Dashboard
        icon: homepage
    - Glances:
        href: http://192.168.1.100:61208
        description: Métricas
        icon: glances
    - Portainer:
        href: https://192.168.1.100:9443
        description: Docker management
        icon: portainer

- Streaming:
    - Sunshine:
        href: https://192.168.1.100:47990
        description: Sunshine UI
        icon: sunshine

- Storage:
    - Nextcloud:
        href: http://192.168.1.100:8080
        description: Archivos (LAN)
        icon: nextcloud
